{
    "openapi": "3.0.2",
    "info": {
        "title": "指标模型",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "https://{host}:{port}/api",
            "description": "host:localhost;port:13020",
            "variables": {
                "host": {
                    "default": "服务器ip"
                },
                "port": {
                    "default": "默认端口"
                }
            }
        }
    ],
    "paths": {
        "/data-model/v1/metric-models": {
            "get": {
                "parameters": [
                    {
                        "name": "name_pattern",
                        "description": "根据指标模型名称模糊查询，默认为空. 与 name 不能同时存在",
                        "schema": {
                            "type": "string"
                        },
                        "in": "query"
                    },
                    {
                        "name": "name",
                        "description": "根据指标模型名称精确过滤，默认为空.与 name_pattern 不能同时存在",
                        "schema": {
                            "type": "string"
                        },
                        "in": "query"
                    },
                    {
                        "name": "metric_type",
                        "description": "指标类型，默认为空",
                        "schema": {
                            "enum": [
                                "atomic",
                                "complex"
                            ],
                            "type": "string"
                        },
                        "in": "query"
                    },
                    {
                        "name": "query_type",
                        "description": "指标查询语言，默认为空",
                        "schema": {
                            "enum": [
                                "promql"
                            ],
                            "type": "string"
                        },
                        "in": "query"
                    },
                    {
                        "name": "sort",
                        "description": "排序类型，默认是update_time",
                        "schema": {
                            "enum": [
                                "update_time",
                                "model_name"
                            ],
                            "type": "string"
                        },
                        "in": "query"
                    },
                    {
                        "name": "direction",
                        "description": "排序结果方向，可选asc、desc。\n默认desc",
                        "schema": {
                            "enum": [
                                "asc",
                                "desc"
                            ],
                            "type": "string"
                        },
                        "in": "query"
                    },
                    {
                        "name": "offset",
                        "description": "开始响应的项目的偏移量\t\n范围需大于等于0，默认值0",
                        "schema": {
                            "format": "int64",
                            "type": "integer"
                        },
                        "in": "query"
                    },
                    {
                        "name": "limit",
                        "description": "每页最多可返回的项目数；\n分页可选1-1000，-1表示不分页；\n默认值10",
                        "schema": {
                            "format": "int64",
                            "type": "integer"
                        },
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ListMetricModels"
                                },
                                "examples": {
                                    "list_metric_models": {
                                        "value": {
                                            "entries": [
                                                {
                                                    "id": 86,
                                                    "name": "主机cpu使用率",
                                                    "metric_type": "atomic",
                                                    "data_view_name": "主机监控",
                                                    "query_type": "promql",
                                                    "formula": "avg(irate(node_cpu_seconds_total{name=~\"node-14-35\",mode=\"system\"}[5m]))by(name)",
                                                    "date_field": "@timestamp",
                                                    "date_format": "epoch_millis",
                                                    "metric_field": "value",
                                                    "unit_type": "timeUnit",
                                                    "unit": "ms",
                                                    "tags": [
                                                        "some text",
                                                        "some text"
                                                    ],
                                                    "custom_attribute": {
                                                        "attribute": "abc"
                                                    },
                                                    "comment": "主机cpu使用率",
                                                    "update_time": "2022-11-24 17:06:43"
                                                }
                                            ],
                                            "total_count": 1
                                        }
                                    }
                                }
                            }
                        },
                        "description": "查询成功，返回指标模型的列表"
                    },
                    "400": {
                        "$ref": "#/components/responses/400BadRequest"
                    },
                    "500": {
                        "$ref": "#/components/responses/500InternalError"
                    }
                },
                "summary": "查询指标模型列表"
            },
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/components/schemas/ReqMetricModel"
                                }
                            },
                            "examples": {
                                "新增一个": {
                                    "value": [
                                        {
                                            "name": "主机-cpu使用率",
                                            "metric_type": "原子指标",
                                            "data_view_name": "主机监控",
                                            "query_type": "promql",
                                            "formula": "avg(irate(node_cpu_seconds_total{name=~\"node-14-35\",mode=\"system\"}[5m]))by(name)",
                                            "date_field": "@timestamp",
                                            "date_format": "epoch_millis",
                                            "metric_field": "value",
                                            "unit_type": "timeUnit",
                                            "unit": "ms",
                                            "tags": [
                                                "some text",
                                                "some text"
                                            ],
                                            "custom_attribute": {
                                                "link": "指标b"
                                            },
                                            "comment": "主机cpu使用率"
                                        }
                                    ]
                                },
                                "导入多个": {
                                    "value": [
                                        {
                                            "name": "主机cpu使用率",
                                            "metric_type": "atomic",
                                            "data_view_name": "主机监控",
                                            "query_type": "promql",
                                            "formula": "avg(irate(node_cpu_seconds_total{name=~\"node-14-35\",mode=\"system\"}[5m]))by(name)",
                                            "date_field": "@timestamp",
                                            "date_format": "epoch_millis",
                                            "metric_field": "value",
                                            "timeUnit": "timeUnit",
                                            "unit": "ms",
                                            "tags": [
                                                "some text",
                                                "some text"
                                            ],
                                            "custom_attribute": {
                                                "link": "指标a"
                                            },
                                            "comment": "主机cpu使用率"
                                        },
                                        {
                                            "name": "主机总内存",
                                            "metric_type": "atomic",
                                            "data_view_name": "主机监控",
                                            "query_type": "promql",
                                            "formula": "node_memory_MemTotal_bytes{name=~\"node-14-35\"}",
                                            "date_field": "@timestamp",
                                            "date_format": "epoch_millis",
                                            "metric_field": "value",
                                            "unit_type": "storeUnit",
                                            "unit": "Byte",
                                            "tags": [
                                                "some text",
                                                "some text"
                                            ],
                                            "custom_attribute": {
                                                "link": "指标a"
                                            },
                                            "comment": "主机总内存"
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                        "headers": {
                            "Location": {
                                "schema": {
                                    "format": "uri",
                                    "type": "string"
                                },
                                "description": "`/api/data-model/v1/metric_models/{ids}`"
                            }
                        },
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/MetricModelId"
                                    }
                                },
                                "examples": {
                                    "新增一个": {
                                        "value": [
                                            {
                                                "id": 69
                                            }
                                        ]
                                    },
                                    "导入多个": {
                                        "value": [
                                            {
                                                "id": 17
                                            },
                                            {
                                                "id": 96
                                            }
                                        ]
                                    }
                                }
                            }
                        },
                        "description": "新增/导入成功"
                    },
                    "400": {
                        "$ref": "#/components/responses/400BadRequest"
                    },
                    "500": {
                        "$ref": "#/components/responses/500InternalError"
                    }
                },
                "summary": "创建指标模型",
                "description": "创建指标模型，支持批量创建"
            }
        },
        "/data-model/v1/metric-models/{id}": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/DataMetricModelWithDetailDataView"
                                },
                                "examples": {
                                    "exp": {
                                        "value": {
                                            "id": 72,
                                            "name": "some text",
                                            "metric_type": "complex",
                                            "data_view_name": "some text",
                                            "data_view": {
                                                "indices": [
                                                    "some text",
                                                    "some text"
                                                ],
                                                "must_filter": "some text"
                                            },
                                            "query_type": "promql",
                                            "formula": "some text",
                                            "date_field": "some text",
                                            "date_format": "epoch_millis",
                                            "metric_field": "some text",
                                            "unit_type": "storeUnit",
                                            "unit": "Mbps",
                                            "tags": [
                                                "some text",
                                                "some text"
                                            ],
                                            "custom_attribute": {

                                            },
                                            "comment": "some text",
                                            "update_time": "some text"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "$ref": "#/components/responses/400BadRequest"
                    },
                    "500": {
                        "$ref": "#/components/responses/500InternalError"
                    }
                },
                "summary": "按 id 取指标模型对象信息"
            },
            "put": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/UpdateMetricModel"
                            },
                            "examples": {
                                "exp": {
                                    "value": {
                                        "name": "some text",
                                        "metric_type": "atomic",
                                        "data_view_name": "some text",
                                        "query_type": "promql",
                                        "formula": "some text",
                                        "date_field": "@timestamp",
                                        "date_format": "epoch_millis",
                                        "metric_field": "value",
                                        "unit_type": "timeUnit",
                                        "unit": "ms",
                                        "tags": [
                                            "some text",
                                            "some text"
                                        ],
                                        "custom_attribute": {
                                            "link": "指标a"
                                        },
                                        "comment": "some text"
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "parameters": [
                    {
                        "name": "id",
                        "description": "指标模型 id",
                        "schema": {
                            "type": "integer"
                        },
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "400": {
                        "$ref": "#/components/responses/400BadRequest"
                    },
                    "500": {
                        "$ref": "#/components/responses/500InternalError"
                    },
                    "404": {
                        "$ref": "#/components/responses/404MetricModelNotFound"
                    },
                    "204": {
                        "description": "修改成功"
                    }
                },
                "summary": "修改指标模型"
            },
            "parameters": [
                {
                    "name": "id",
                    "description": "指标模型 id",
                    "schema": {
                        "type": "integer"
                    },
                    "in": "path",
                    "required": true
                }
            ]
        },
        "/data-model/v1/metric-models/{ids}": {
            "delete": {
                "parameters": [
                    {
                        "examples": {
                            "exp": {
                                "value": "<1,15,56>"
                            }
                        },
                        "name": "ids",
                        "description": "指标模型id数组",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        },
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "删除成功"
                    },
                    "404": {
                        "$ref": "#/components/responses/404MetricModelNotFound"
                    },
                    "500": {
                        "$ref": "#/components/responses/500InternalError"
                    }
                },
                "summary": "删除指标模型",
                "description": "按 id 删除，可批量删除"
            },
            "parameters": [
                {
                    "examples": {
                        "exp": {
                            "value": "<1,15,56>"
                        }
                    },
                    "name": "ids",
                    "description": "指标模型id数组",
                    "schema": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    },
                    "in": "path",
                    "required": true
                }
            ]
        }
    },
    "components": {
        "schemas": {
            "Error": {
                "description": "",
                "required": [
                    "description",
                    "error_code",
                    "error_detail",
                    "error_link",
                    "solution"
                ],
                "type": "object",
                "properties": {
                    "description": {
                        "description": "错误描述",
                        "type": "string"
                    },
                    "error_code": {
                        "description": "错误码",
                        "type": "string"
                    },
                    "error_detail": {
                        "description": "错误详情",
                        "type": "string"
                    },
                    "error_link": {
                        "description": "错误链接",
                        "type": "string"
                    },
                    "solution": {
                        "description": "处理建议",
                        "type": "string"
                    }
                },
                "example": {
                    "description": "some text",
                    "error_code": "some text",
                    "error_detail": "some text",
                    "error_link": "some text",
                    "solution": "some text"
                }
            },
            "CustomAttributeMap": {
                "title": "Root Type for CustomAttributeMap",
                "description": "自定义属性map",
                "type": "object",
                "properties": {
                    "key": {
                        "description": "自定义属性的key值",
                        "type": "string"
                    }
                },
                "example": {
                    "key": "value"
                }
            },
            "DataView": {
                "description": "数据视图的信息。当前版本是获取日志分组的过滤条件",
                "required": [
                    "indices",
                    "must_filter"
                ],
                "type": "object",
                "properties": {
                    "indices": {
                        "description": "日志分组包含的日志库信息",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "must_filter": {
                        "description": "日志分组的dsl过滤条件语句",
                        "type": "string"
                    }
                },
                "example": {
                    "indices": [
                        "some text",
                        "some text"
                    ],
                    "must_filter": "some text"
                }
            },
            "string": {
                "description": "<uri>\n修改指标模型",
                "type": "object"
            },
            "MetricModelId": {
                "description": "",
                "required": [
                    "model_id"
                ],
                "type": "object",
                "properties": {
                    "id": {
                        "description": "指标模型id",
                        "type": "integer"
                    }
                },
                "example": {
                    "id": 98
                }
            },
            "ListMetricModels": {
                "description": "",
                "required": [
                    "entries",
                    "total_count"
                ],
                "type": "object",
                "properties": {
                    "entries": {
                        "description": "条目列表",
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/DataMetricModel"
                        }
                    },
                    "total_count": {
                        "description": "总条数",
                        "type": "integer"
                    }
                },
                "example": {
                    "entries": [
                        {
                            "id": 86,
                            "name": "主机cpu使用率",
                            "metric_type": "原子指标",
                            "data_view_name": "主机监控",
                            "query_type": "promql",
                            "formula": "avg(irate(node_cpu_seconds_total{name=~\"node-14-35\",mode=\"system\"}[5m]))by(name)",
                            "date_field": "@timestamp",
                            "date_format": "epoch_millis",
                            "metric_field": "value",
                            "unit_type": "timeUnit",
                            "unit": "ms",
                            "tags": [
                                "some text",
                                "some text"
                            ],
                            "custom_attribute": {
                                "key": "some text"
                            },
                            "comment": "主机cpu使用率",
                            "update_time": "2022-11-24 17:06:43"
                        }
                    ],
                    "total_count": 1
                }
            },
            "ReqMetricModel": {
                "description": "",
                "required": [
                    "metric_model_name",
                    "metric_type",
                    "query_type",
                    "formula",
                    "data_view_name",
                    "model_name",
                    "name",
                    "unit_type",
                    "metric_field",
                    "unit"
                ],
                "type": "object",
                "properties": {
                    "name": {
                        "description": "指标模型名称",
                        "type": "string"
                    },
                    "metric_type": {
                        "description": "指标类型",
                        "enum": [
                            "atomic",
                            "complex"
                        ],
                        "type": "string"
                    },
                    "data_view_name": {
                        "description": "数据视图名称",
                        "type": "string"
                    },
                    "query_type": {
                        "description": "指标查询语言。根据 category 和 datasource 来展示指标查询语言列表",
                        "enum": [
                            "promql"
                        ],
                        "type": "string"
                    },
                    "formula": {
                        "description": "计算公式",
                        "type": "string"
                    },
                    "date_field": {
                        "description": "时间字段。当查询语言是 promql 时，此字段值为 @timestamp。",
                        "type": "string"
                    },
                    "date_format": {
                        "description": "时间格式。当查询语言是 promql 时，此字段值为 epoch_millis。",
                        "enum": [
                            "epoch_millis"
                        ],
                        "type": "string"
                    },
                    "metric_field": {
                        "description": "度量字段。当查询语言是 promql 时，此字段值为 value。",
                        "type": "string"
                    },
                    "unit_type": {
                        "description": "单位类型",
                        "enum": [
                            "numUnit",
                            "storeUnit",
                            "percent",
                            "transmissionRate",
                            "timeUnit"
                        ],
                        "type": "string"
                    },
                    "unit": {
                        "description": "度量单位",
                        "enum": [
                            "none",
                            "K",
                            "Mil",
                            "Bil",
                            "Tri",
                            "bit",
                            "Byte",
                            "KB",
                            "MB",
                            "GB",
                            "TB",
                            "PB",
                            "%",
                            "bps",
                            "Kbps",
                            "Mbps",
                            "μs",
                            "ms",
                            "s",
                            "m",
                            "h",
                            "day",
                            "week",
                            "month",
                            "year"
                        ],
                        "type": "string"
                    },
                    "tags": {
                        "description": "标签。用于业务标识",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "custom_attribute": {
                        "description": "自定义属性，map，可以包含任意键值对",
                        "type": "object",
                        "additionalProperties": true
                    },
                    "comment": {
                        "description": "指标模型备注",
                        "type": "string"
                    }
                },
                "example": {
                    "name": "主机-cpu使用率",
                    "metric_type": "原子指标",
                    "data_view_name": "主机监控",
                    "query_type": "promql",
                    "formula": "avg(irate(node_cpu_seconds_total{name=~\"node-14-35\",mode=\"system\"}[5m]))by(name)",
                    "date_field": "@timestamp",
                    "date_format": "epoch_second",
                    "metric_field": "value",
                    "unit_type": "numUnit",
                    "unit": "'Mil'",
                    "tags": [
                        "some text",
                        "some text"
                    ],
                    "custom_attribute": {
                        "link": "指标b"
                    },
                    "comment": "主机cpu使用率"
                }
            },
            "DataMetricModel": {
                "description": "",
                "required": [
                    "model_name",
                    "model_id",
                    "metric_type",
                    "query_type",
                    "formula",
                    "data_view_name",
                    "comment",
                    "custom_attribute",
                    "tags",
                    "update_time",
                    "name",
                    "id",
                    "metric_field",
                    "date_field",
                    "date_format",
                    "unit",
                    "unit_type"
                ],
                "type": "object",
                "properties": {
                    "id": {
                        "description": "指标模型 id",
                        "type": "integer"
                    },
                    "name": {
                        "description": "指标模型名称",
                        "type": "string"
                    },
                    "metric_type": {
                        "description": "指标类型，分原子指标和复合指标。",
                        "enum": [
                            "atomic",
                            "complex"
                        ],
                        "type": "string"
                    },
                    "data_view_name": {
                        "description": "数据视图名称",
                        "type": "string"
                    },
                    "query_type": {
                        "description": "指标查询语言。根据 category 和 datasource 来展示指标查询语言列表。",
                        "enum": [
                            "promql"
                        ],
                        "type": "string"
                    },
                    "formula": {
                        "description": "计算公式",
                        "type": "string"
                    },
                    "date_field": {
                        "description": "时间字段。当查询语言是 promql 时，此字段值为 @timestamp。",
                        "type": "string"
                    },
                    "date_format": {
                        "description": "时间格式。当查询语言是 promql 时，此字段值为 epoch_millis。",
                        "enum": [
                            "epoch_millis"
                        ],
                        "type": "string"
                    },
                    "metric_field": {
                        "description": "度量字段。当查询语言是 promql 时，此字段值为 value。",
                        "type": "string"
                    },
                    "unit_type": {
                        "description": "单位类型",
                        "enum": [
                            "numUnit",
                            "storeUnit",
                            "percent",
                            "transmissionRate",
                            "timeUnit"
                        ],
                        "type": "string"
                    },
                    "unit": {
                        "description": "度量单位",
                        "enum": [
                            "none",
                            "K",
                            "Mil",
                            "Bil",
                            "Tri",
                            "bit",
                            "Byte",
                            "KB",
                            "MB",
                            "GB",
                            "TB",
                            "PB",
                            "%",
                            "bps",
                            "Kbps",
                            "Mbps",
                            "μs",
                            "ms",
                            "s",
                            "m",
                            "h",
                            "day",
                            "week",
                            "month",
                            "year"
                        ],
                        "type": "string"
                    },
                    "tags": {
                        "description": "标签。 （可以为空）",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "custom_attribute": {
                        "description": "自定义属性（可以为空），map，可以包含任意键值对",
                        "type": "object",
                        "additionalProperties": true
                    },
                    "comment": {
                        "description": "指标模型备注（可以为空）",
                        "type": "string"
                    },
                    "update_time": {
                        "description": "更新时间",
                        "pattern": "yyyy-MM-dd hh:mm:ss",
                        "type": "string"
                    }
                },
                "example": {
                    "id": 33,
                    "name": "some text",
                    "metric_type": "complex",
                    "data_view_name": "some text",
                    "query_type": "promql",
                    "formula": "some text",
                    "date_field": "some text",
                    "date_format": "epoch_second",
                    "metric_field": "some text",
                    "unit_type": "numUnit",
                    "unit": "Byte",
                    "tags": [
                        "some text",
                        "some text"
                    ],
                    "custom_attribute": {

                    },
                    "comment": "some text",
                    "update_time": "some text"
                }
            },
            "DataMetricModelWithDetailDataView": {
                "description": "",
                "required": [
                    "name",
                    "id",
                    "metric_type",
                    "query_type",
                    "formula",
                    "data_view",
                    "data_view_name",
                    "comment",
                    "custom_attribute",
                    "tags",
                    "update_time",
                    "date_field",
                    "date_format",
                    "metric_field",
                    "unit",
                    "unit_type"
                ],
                "type": "object",
                "properties": {
                    "id": {
                        "description": "指标模型 id",
                        "type": "integer"
                    },
                    "name": {
                        "description": "指标模型名称",
                        "type": "string"
                    },
                    "metric_type": {
                        "description": "指标类型，分原子指标和复合指标。",
                        "enum": [
                            "atomic",
                            "complex"
                        ],
                        "type": "string"
                    },
                    "data_view_name": {
                        "description": "数据视图名称",
                        "type": "string"
                    },
                    "data_view": {
                        "$ref": "#/components/schemas/DataView",
                        "description": "数据视图信息"
                    },
                    "query_type": {
                        "description": "指标查询语言。根据 category 和 datasource 来展示指标查询语言列表。",
                        "enum": [
                            "promql"
                        ],
                        "type": "string"
                    },
                    "formula": {
                        "description": "计算公式",
                        "type": "string"
                    },
                    "date_field": {
                        "description": "时间字段。当查询语言是 promql 时，此字段值为 @timestamp。",
                        "type": "string"
                    },
                    "date_format": {
                        "description": "时间格式。当查询语言是 promql 时，此字段值为 epoch_millis。",
                        "enum": [
                            "epoch_millis"
                        ],
                        "type": "string"
                    },
                    "metric_field": {
                        "description": "度量字段。当查询语言是 promql 时，此字段值为 value。",
                        "type": "string"
                    },
                    "unit_type": {
                        "description": "单位类型",
                        "enum": [
                            "numUnit",
                            "storeUnit",
                            "percent",
                            "transmissionRate",
                            "timeUnit"
                        ],
                        "type": "string"
                    },
                    "unit": {
                        "description": "度量单位",
                        "enum": [
                            "none",
                            "K",
                            "Mil",
                            "Bil",
                            "Tri",
                            "bit",
                            "Byte",
                            "KB",
                            "MB",
                            "GB",
                            "TB",
                            "PB",
                            "%",
                            "bps",
                            "Kbps",
                            "Mbps",
                            "μs",
                            "ms",
                            "s",
                            "m",
                            "h",
                            "day",
                            "week",
                            "month",
                            "year"
                        ],
                        "type": "string"
                    },
                    "tags": {
                        "description": "标签（可以为空）",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "custom_attribute": {
                        "description": "自定义属性（可以为空），map，可以包含任意键值对",
                        "type": "object",
                        "additionalProperties": true
                    },
                    "comment": {
                        "description": "指标模型备注（可以为空）",
                        "type": "string"
                    },
                    "update_time": {
                        "description": "更新时间",
                        "pattern": "yyyy-MM-dd hh:mm:ss",
                        "type": "string"
                    }
                },
                "example": {
                    "id": 23,
                    "name": "some text",
                    "metric_type": "some text",
                    "data_view_name": "some text",
                    "data_view": {
                        "indices": [
                            "some text",
                            "some text"
                        ],
                        "must_filter": "some text"
                    },
                    "query_type": "some text",
                    "formula": "some text",
                    "date_field": "@timestamp",
                    "date_format": "epoch_second",
                    "metric_field": "value",
                    "unit_type": "timeUnit",
                    "unit": "ms",
                    "tags": [
                        "some text",
                        "some text"
                    ],
                    "custom_attribute": {
                        "key": "some text"
                    },
                    "comment": "some text",
                    "update_time": "some text"
                }
            },
            "UpdateMetricModel": {
                "description": "",
                "required": [
                    "metric_type",
                    "query_type",
                    "formula",
                    "data_view_name",
                    "name",
                    "metric_field",
                    "unit_type",
                    "unit"
                ],
                "type": "object",
                "properties": {
                    "name": {
                        "description": "指标模型名称",
                        "type": "string"
                    },
                    "metric_type": {
                        "description": "指标类型",
                        "enum": [
                            "atomic",
                            "complex"
                        ],
                        "type": "string"
                    },
                    "data_view_name": {
                        "description": "数据视图名称",
                        "type": "string"
                    },
                    "query_type": {
                        "description": "指标查询语言",
                        "enum": [
                            "promql"
                        ],
                        "type": "string"
                    },
                    "formula": {
                        "description": "计算公式",
                        "type": "string"
                    },
                    "date_field": {
                        "description": "时间字段。当查询语言是 promql 时，此字段值为 @timestamp。",
                        "type": "string"
                    },
                    "date_format": {
                        "description": "时间格式。当查询语言是 promql 时，此字段值为 epoch_millis。",
                        "enum": [
                            "epoch_millis"
                        ],
                        "type": "string"
                    },
                    "metric_field": {
                        "description": "度量字段。当查询语言是 promql 时，此字段值为 value。",
                        "type": "string"
                    },
                    "unit_type": {
                        "description": "单位类型",
                        "enum": [
                            "numUnit",
                            "storeUnit",
                            "percent",
                            "transmissionRate",
                            "timeUnit"
                        ],
                        "type": "string"
                    },
                    "unit": {
                        "description": "度量单位",
                        "enum": [
                            "none",
                            "K",
                            "Mil",
                            "Bil",
                            "Tri",
                            "bit",
                            "Byte",
                            "KB",
                            "MB",
                            "GB",
                            "TB",
                            "PB",
                            "%",
                            "bps",
                            "Kbps",
                            "Mbps",
                            "μs",
                            "ms",
                            "s",
                            "m",
                            "h",
                            "day",
                            "week",
                            "month",
                            "year"
                        ],
                        "type": "string"
                    },
                    "tags": {
                        "description": "标签",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "custom_attribute": {
                        "description": "自定义属性（可以为空），map，可以包含任意键值对",
                        "type": "object",
                        "additionalProperties": true
                    },
                    "comment": {
                        "description": "指标模型备注",
                        "type": "string"
                    }
                },
                "example": {
                    "name": "主机cpu使用率",
                    "metric_type": "原子指标",
                    "data_view_name": "主机监控",
                    "query_type": "promql",
                    "formula": "avg(irate(node_cpu_seconds_total{name=~\"node-14-35\",mode=\"system\"}[5m]))by(name)",
                    "date_field": "some text",
                    "date_format": "epoch_second",
                    "metric_field": "some text",
                    "unit_type": "transmissionRate",
                    "unit": "bps",
                    "tags": [
                        "some text",
                        "some text"
                    ],
                    "custom_attribute": {
                        "key": "some text"
                    },
                    "comment": "some text"
                }
            }
        },
        "responses": {
            "500InternalError": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Error"
                        },
                        "examples": {
                            "exp": {
                                "value": {
                                    "description": "internel server error",
                                    "error_code": "DataModel.MetricModel.InternalError",
                                    "error_detail": "some text",
                                    "error_link": "some text",
                                    "solution": "some text"
                                }
                            }
                        }
                    }
                },
                "description": "内部错误"
            },
            "400BadRequest": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Error"
                        },
                        "examples": {
                            "exp": {
                                "value": {
                                    "description": "Invalid Parameter",
                                    "error_code": "DataModel.MetricModel.InvalidParameter",
                                    "error_detail": "some text",
                                    "error_link": "some text",
                                    "solution": "some text"
                                }
                            }
                        }
                    }
                },
                "description": "参数错误"
            },
            "400InvalidOffset": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Error"
                        },
                        "examples": {
                            "exp": {
                                "value": {
                                    "description": "some text",
                                    "error_code": "DataDict.BadRequest.InvalidOffset",
                                    "error_detail": "some text",
                                    "error_link": "some text",
                                    "solution": "some text"
                                }
                            }
                        }
                    }
                },
                "description": ""
            },
            "400InvalidLimit": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Error"
                        },
                        "examples": {
                            "exp": {
                                "value": {
                                    "description": "some text",
                                    "error_code": "DataDict.BadRequest.InvalidLimit",
                                    "error_detail": "some text",
                                    "error_link": "some text",
                                    "solution": "some text"
                                }
                            }
                        }
                    }
                },
                "description": ""
            },
            "400InvalidDirection": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Error"
                        },
                        "examples": {
                            "exp": {
                                "value": {
                                    "description": "some text",
                                    "error_code": "DataDict.BadRequest.InvalidDirection",
                                    "error_detail": "some text",
                                    "error_link": "some text",
                                    "solution": "some text"
                                }
                            }
                        }
                    }
                },
                "description": ""
            },
            "400InvalidSort": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Error"
                        },
                        "examples": {
                            "exp": {
                                "value": {
                                    "description": "some text",
                                    "error_code": "DataDict.BadRequest.InvalidSort",
                                    "error_detail": "some text",
                                    "error_link": "some text",
                                    "solution": "some text"
                                }
                            }
                        }
                    }
                },
                "description": ""
            },
            "404MetricModelNotFound": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Error"
                        },
                        "examples": {
                            "exp": {
                                "value": {
                                    "error_code": "DataModel.MetricModel.ResourceNotFound",
                                    "description": "MetricModel Not Found",
                                    "error_detail": "some text",
                                    "error_link": "some text",
                                    "solution": "some text"
                                }
                            }
                        }
                    }
                },
                "description": "MetricModel未找到"
            },
            "400MetricModelNameExist": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Error"
                        },
                        "examples": {
                            "exp": {
                                "value": {
                                    "description": "some text",
                                    "error_code": "DataDict.BadRequest.DictItemKeyExist",
                                    "error_detail": "some text",
                                    "error_link": "some text",
                                    "solution": "some text"
                                }
                            }
                        }
                    }
                },
                "description": "指标模型名称已存在"
            },
            "400MetricModelNameNull": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Error"
                        },
                        "examples": {
                            "exp": {
                                "value": {
                                    "description": "some text",
                                    "error_code": "DataDict.BadRequest.DictItemKeyOrValueNull",
                                    "error_detail": "some text",
                                    "error_link": "some text",
                                    "solution": "some text"
                                }
                            }
                        }
                    }
                },
                "description": "指标模型名称为空"
            },
            "404DataViewNotFound": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Error"
                        },
                        "examples": {
                            "exp": {
                                "value": {
                                    "error_code": "DataDict.NotFound.DictionaryItemNotFound",
                                    "description": "DataDictionaryItem Not Found",
                                    "error_detail": "some text",
                                    "error_link": "some text",
                                    "solution": "some text"
                                }
                            }
                        }
                    }
                },
                "description": "数据视图未找到"
            },
            "400InvalidMetricModelName": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Error"
                        },
                        "examples": {
                            "exp": {
                                "value": {
                                    "description": "some text",
                                    "error_code": "DataDict.BadRequest.InvalidDictItemKeyOrValue",
                                    "error_detail": "some text",
                                    "error_link": "some text",
                                    "solution": "some text"
                                }
                            }
                        }
                    }
                },
                "description": "指标模型名称不合法"
            },
            "400DataViewNameNull": {
                "description": "数据视图名称为空"
            },
            "400MetricTypeNull": {
                "description": "指标类型为空"
            },
            "400FormulaNull": {
                "description": "计算公式为空"
            }
        }
    }
}