{
    "openapi": "3.0.2",
    "info": {
        "title": "Feed Ingester Opentelemetry Trace接收",
        "version": "1.0.0",
        "description": "A brand new API with no content.  Go nuts!"
    },
    "paths": {
        "/api/feed_ingester/v1/jobs/{job_id}/events": {
            "description": "接收接口url",
            "post": {
                "requestBody": {
                    "description": "参数名与opentelemetry标准参数一致，具体含义直接参考opentelemetry标准，兼容的opentelemetry版本为v1版本(v1.0.0-v1.9.0)",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/components/schemas/SingleTrace"
                                }
                            },
                            "examples": {
                                "common ": {
                                    "value": [
                                        {
                                            "Name": "拉取服务",
                                            "SpanContext": {
                                                "TraceID": "ab4fe1de2d9c951411bbdbc3533d747f",
                                                "SpanID": "44c39ef193f3e08a",
                                                "TraceFlags": "01",
                                                "TraceState": "rojo=00f067aa0ba902b7,congo=t61rcWkgMzE",
                                                "Remote": false
                                            },
                                            "Parent": {
                                                "TraceID": "ab4fe1de2d9c951411bbdbc3533d747f",
                                                "SpanID": "dbff9e1d80069b58",
                                                "TraceFlags": "01",
                                                "TraceState": "rojo=00f067aa0ba902b7,congo=t61rcWkgMzE",
                                                "Remote": false
                                            },
                                            "SpanKind": 1,
                                            "StartTime": "2022-04-29T18:52:58.114304Z",
                                            "EndTime": "2022-04-29T18:52:58.114435Z",
                                            "Attributes": [
                                                {
                                                    "Key": "输入的数字：",
                                                    "Value": {
                                                        "Type": "STRING",
                                                        "Value": "45"
                                                    }
                                                }
                                            ],
                                            "Events": [
                                                {
                                                    "Name": "Nice operation!",
                                                    "Attributes": [
                                                        {
                                                            "Key": "bogons",
                                                            "Value": {
                                                                "Type": "INT",
                                                                "Value": 100
                                                            }
                                                        }
                                                    ],
                                                    "DroppedAttributeCount": 0,
                                                    "Time": "2022-04-29T18:52:58.114435Z"
                                                }
                                            ],
                                            "Links": [
                                                {
                                                    "TraceID": "ab4fe1de2d9c951411bbdbc3533d747h",
                                                    "SpanID": "dbff9e1d80069b59",
                                                    "TraceState": "rojo=00f067aa0ba902b7,congo=t61rcWkgMzE",
                                                    "Attributes": [
                                                        {
                                                            "Key": "num1",
                                                            "Value": {
                                                                "Type": "INT",
                                                                "Value": 100
                                                            }
                                                        }
                                                    ]
                                                }
                                            ],
                                            "Status": {
                                                "Code": "Unset",
                                                "Description": ""
                                            },
                                            "DroppedAttributes": 0,
                                            "DroppedEvents": 0,
                                            "DroppedLinks": 0,
                                            "ChildSpanCount": 0,
                                            "Resource": [
                                                {
                                                    "Key": "service.name",
                                                    "Value": {
                                                        "Type": "STRING",
                                                        "Value": "斐波那契数列"
                                                    }
                                                },
                                                {
                                                    "Key": "service.version",
                                                    "Value": {
                                                        "Type": "STRING",
                                                        "Value": "版本1.0.1"
                                                    }
                                                },
                                                {
                                                    "Key": "telemetry.sdk.language",
                                                    "Value": {
                                                        "Type": "STRING",
                                                        "Value": "go"
                                                    }
                                                },
                                                {
                                                    "Key": "telemetry.sdk.name",
                                                    "Value": {
                                                        "Type": "STRING",
                                                        "Value": "opentelemetry"
                                                    }
                                                },
                                                {
                                                    "Key": "telemetry.sdk.version",
                                                    "Value": {
                                                        "Type": "STRING",
                                                        "Value": "1.9.0"
                                                    }
                                                },
                                                {
                                                    "Key": "环境",
                                                    "Value": {
                                                        "Type": "STRING",
                                                        "Value": "样例"
                                                    }
                                                }
                                            ],
                                            "InstrumentationLibrary": {
                                                "Name": "斐波",
                                                "Version": "",
                                                "SchemaURL": ""
                                            }
                                        },
                                        {
                                            "Name": "计算服务",
                                            "SpanContext": {
                                                "TraceID": "ab4fe1de2d9c951411bbdbc3533d754k",
                                                "SpanID": "44c39ef193f3e25d",
                                                "TraceFlags": "01",
                                                "TraceState": "rojo=00f067aa0ba902b7,congo=t61rcWkgMzE",
                                                "Remote": false
                                            },
                                            "Parent": {
                                                "TraceID": "ab4fe1de2d9c951411bbdbc3533d747f",
                                                "SpanID": "dbff9e1d80069b58",
                                                "TraceFlags": "01",
                                                "TraceState": "rojo=00f067aa0ba902b7,congo=t61rcWkgMzE",
                                                "Remote": false
                                            },
                                            "SpanKind": 1,
                                            "StartTime": "2022-04-29T18:52:58.114304Z",
                                            "EndTime": "2022-04-29T18:52:58.114435Z",
                                            "Attributes": [
                                                {
                                                    "Key": "输入的数字：",
                                                    "Value": {
                                                        "Type": "STRING",
                                                        "Value": "45"
                                                    }
                                                }
                                            ],
                                            "Events": [
                                                {
                                                    "Name": "Nice operation!",
                                                    "Attributes": [
                                                        {
                                                            "Key": "bogons",
                                                            "Value": {
                                                                "Type": "INT",
                                                                "Value": 100
                                                            }
                                                        }
                                                    ],
                                                    "DroppedAttributeCount": 0,
                                                    "Time": "2022-04-29T18:52:58.114435Z"
                                                }
                                            ],
                                            "Links": [
                                                {
                                                    "TraceID": "ab4fe1de2d9c951411bbdbc3533d754f",
                                                    "SpanID": "44c39ef193f3e25f",
                                                    "TraceState": "rojo=00f067aa0ba902b7,congo=t61rcWkgMzE",
                                                    "Attributes": [
                                                        {
                                                            "Key": "numk",
                                                            "Value": {
                                                                "Type": "INT",
                                                                "Value": 100
                                                            }
                                                        }
                                                    ]
                                                }
                                            ],
                                            "Status": {
                                                "Code": "Unset",
                                                "Description": ""
                                            },
                                            "DroppedAttributes": 0,
                                            "DroppedEvents": 0,
                                            "DroppedLinks": 0,
                                            "ChildSpanCount": 0,
                                            "Resource": [
                                                {
                                                    "Key": "service.name",
                                                    "Value": {
                                                        "Type": "STRING",
                                                        "Value": "斐波那契数列"
                                                    }
                                                },
                                                {
                                                    "Key": "service.version",
                                                    "Value": {
                                                        "Type": "STRING",
                                                        "Value": "版本1.0.1"
                                                    }
                                                },
                                                {
                                                    "Key": "telemetry.sdk.language",
                                                    "Value": {
                                                        "Type": "STRING",
                                                        "Value": "go"
                                                    }
                                                },
                                                {
                                                    "Key": "telemetry.sdk.name",
                                                    "Value": {
                                                        "Type": "STRING",
                                                        "Value": "opentelemetry"
                                                    }
                                                },
                                                {
                                                    "Key": "telemetry.sdk.version",
                                                    "Value": {
                                                        "Type": "STRING",
                                                        "Value": "1.9.0"
                                                    }
                                                },
                                                {
                                                    "Key": "环境",
                                                    "Value": {
                                                        "Type": "STRING",
                                                        "Value": "样例"
                                                    }
                                                }
                                            ],
                                            "InstrumentationLibrary": {
                                                "Name": "斐波",
                                                "Version": "",
                                                "SchemaURL": ""
                                            }
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "204": {
                        "description": "添加成功"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                },
                                "examples": {
                                    "FeedIngester.BadRequest.FormatError": {
                                        "value": {
                                            "code": "FeedIngester.BadRequest.FormatError",
                                            "description": "请求体格式错误",
                                            "solution": "检查请求体格式",
                                            "details": {

                                            },
                                            "link": "some text"
                                        }
                                    },
                                    "FeedIngester.BadRequest.JobIdNotFound": {
                                        "value": {
                                            "code": "FeedIngester.BadRequest.JobIdNotFound",
                                            "description": "没有找到对应的job_id",
                                            "solution": "没有找到对应的job_id",
                                            "details": {

                                            },
                                            "link": "some text"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "客户端错误"
                    },
                    "413": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                },
                                "examples": {
                                    "FeedIngester.BadRequest.PayloadTooLarge": {
                                        "value": {
                                            "code": "FeedIngester.BadRequest.PayloadTooLarge",
                                            "description": "请求体长度过长",
                                            "solution": "检查请求体长度",
                                            "details": {

                                            },
                                            "link": ""
                                        }
                                    }
                                }
                            }
                        },
                        "description": "请求体超过限制长度"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Error"
                                },
                                "examples": {
                                    "FeedIngester.InternalError.InternalError": {
                                        "value": {
                                            "code": "FeedIngester.InternalError.InternalError",
                                            "description": "内部错误",
                                            "solution": "some text",
                                            "details": {

                                            },
                                            "link": "some text"
                                        }
                                    },
                                    "FeedIngester.InternalError.OutputError": {
                                        "value": {
                                            "code": "FeedIngester.InternalError.OutputError",
                                            "description": "内部错误(发送错误)",
                                            "solution": "some text",
                                            "details": {

                                            },
                                            "link": "some text"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "内部错误"
                    }
                },
                "summary": "接收trace数据",
                "description": "用于从远程接收trace数据,保证长度限制在5m以内"
            },
            "parameters": [
                {
                    "name": "job_id",
                    "description": "任务所属的job_id",
                    "schema": {
                        "type": "string"
                    },
                    "in": "path",
                    "required": true
                },
                {
                    "examples": {
                        "sync": {
                            "value": "sync"
                        }
                    },
                    "name": "sync",
                    "description": "同步模式，决定使用同步上传方式还是异步上传方式",
                    "schema": {
                        "type": "string"
                    },
                    "in": "header"
                },
                {
                    "examples": {
                        "language": {
                            "value": "zh-CN"
                        },
                        "language2": {
                            "value": "en-US"
                        }
                    },
                    "name": "Accept-Language",
                    "description": "国际化配置项，选择返回错误详情的语言",
                    "schema": {
                        "type": "string"
                    },
                    "in": "header"
                }
            ]
        }
    },
    "components": {
        "schemas": {
            "SpanContext": {
                "description": "描述span的具体信息",
                "required": [
                    "TraceID",
                    "SpanID",
                    "TraceFlags",
                    "TraceState"
                ],
                "type": "object",
                "properties": {
                    "TraceID": {
                        "description": "标识trace",
                        "type": "string"
                    },
                    "SpanID": {
                        "description": "标识span",
                        "type": "string"
                    },
                    "TraceFlags": {
                        "description": "跟踪标志，包含包含有关跟踪的信息的二进制编码",
                        "type": "string"
                    },
                    "TraceState": {
                        "description": "携带特定于系统的配置数据",
                        "type": "string"
                    },
                    "Remote": {
                        "description": "是否具有远程父对象",
                        "type": "boolean"
                    }
                },
                "example": {
                    "TraceID": "ab4fe1de2d9c951411bbdbc3533d747f",
                    "SpanID": "44c39ef193f3e08a",
                    "TraceFlags": "01",
                    "TraceState": "rojo=00f067aa0ba902b7,congo=t61rcWkgMzE",
                    "Remote": false
                }
            },
            "Attributes": {
                "title": "Root Type for Attributes",
                "description": "包含该span的属性的一个数组",
                "required": [
                    "Value",
                    "Key"
                ],
                "type": "object",
                "properties": {
                    "Key": {
                        "description": "标识该属性的key值",
                        "type": "string"
                    },
                    "Value": {
                        "$ref": "#/components/schemas/Value",
                        "description": "包含该属性的类型、值"
                    }
                },
                "example": {
                    "Key": "输入的数字：",
                    "Value": {
                        "Type": "STRING",
                        "Value": "45"
                    }
                }
            },
            "Events": {
                "title": "Root Type for Events",
                "description": "记录该span发生的一些事件信息",
                "required": [
                    "Attributes",
                    "Name",
                    "Time"
                ],
                "type": "object",
                "properties": {
                    "Name": {
                        "description": "该时间的名称",
                        "type": "string"
                    },
                    "Attributes": {
                        "description": "描述在该事件中的属性",
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/Attributes"
                        }
                    },
                    "DroppedAttributeCount": {
                        "description": "该事件中减少的属性个数",
                        "type": "integer"
                    },
                    "Time": {
                        "format": "date-time",
                        "description": "该事件发生的时间，时间戳，接受格式：2022-04-29T18:52:58.114304Z",
                        "type": "string"
                    }
                },
                "example": {
                    "Name": "Nice operation!",
                    "Attributes": [
                        {
                            "Key": "bogons",
                            "Value": {
                                "Type": "INT",
                                "Value": 100
                            }
                        }
                    ],
                    "DroppedAttributeCount": 0,
                    "Time": "2022-04-29T18:52:58.114435Z"
                }
            },
            "Links": {
                "title": "Root Type for Links",
                "description": "相关联的其他的Span的信息",
                "required": [
                    "Attributes",
                    "SpanId",
                    "TraceID",
                    "TraceState"
                ],
                "type": "object",
                "properties": {
                    "TraceID": {
                        "description": "相关联span的traceID",
                        "type": "string"
                    },
                    "SpanId": {
                        "description": "相关联span的spanID",
                        "type": "string"
                    },
                    "TraceState": {
                        "description": "相关联span携带特定于系统的配置数据",
                        "type": "string"
                    },
                    "Attributes": {
                        "description": "相关联的span的属性信息",
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/Attributes"
                        }
                    }
                },
                "example": {
                    "TraceID": "ab4fe1de2d9c951411bbdbc3533d747j",
                    "SpanID": "44c39ef193f3e08f",
                    "TraceState": "rojo=00f067aa0ba902b7,congo=t61rcWkgMzE",
                    "Attributes": [
                        {
                            "Key": "num1",
                            "Value": {
                                "Type": "INT",
                                "Value": 100
                            }
                        }
                    ]
                }
            },
            "Resource": {
                "title": "Root Type for Resource",
                "description": "一些资源字段信息",
                "required": [
                    "Key",
                    "Value"
                ],
                "type": "object",
                "properties": {
                    "Key": {
                        "description": "该资源的key值",
                        "type": "string"
                    },
                    "Value": {
                        "$ref": "#/components/schemas/Value",
                        "description": "包含该资源的类型、值"
                    }
                },
                "example": {
                    "Key": "service.name",
                    "Value": {
                        "Type": "STRING",
                        "Value": "斐波那契数列"
                    }
                }
            },
            "InstrumentationLibrary": {
                "title": "Root Type for InstrumentationLibrary",
                "description": "使用的工具库信息",
                "required": [
                    "Name",
                    "SchemaURL",
                    "Version"
                ],
                "type": "object",
                "properties": {
                    "Name": {
                        "description": "使用工具库的名称",
                        "type": "string"
                    },
                    "Version": {
                        "description": "使用工具库的版本",
                        "type": "string"
                    },
                    "SchemaURL": {
                        "description": "使用工具库的地址",
                        "type": "string"
                    }
                },
                "example": {
                    "Name": "斐波",
                    "Version": "",
                    "SchemaURL": ""
                }
            },
            "SingleTrace": {
                "description": "单个span(总请求体大小控制在5m以内)",
                "required": [
                    "Name",
                    "SpanContext",
                    "Parent",
                    "SpanKind",
                    "StartTime",
                    "EndTime",
                    "Attributes",
                    "Events",
                    "Links",
                    "Status",
                    "Resource"
                ],
                "type": "object",
                "properties": {
                    "Name": {
                        "description": "span名称",
                        "type": "string"
                    },
                    "SpanContext": {
                        "$ref": "#/components/schemas/SpanContext",
                        "description": "该span的具体信息"
                    },
                    "Parent": {
                        "nullable": true,
                        "$ref": "#/components/schemas/SpanContext",
                        "description": "该span的父span的具体信息"
                    },
                    "SpanKind": {
                        "description": "在一次追踪中 Span 及其父子之间的关系",
                        "maximum": 5,
                        "minimum": 0,
                        "type": "integer"
                    },
                    "StartTime": {
                        "format": "date-time",
                        "description": "span开始时间，时间戳，接受格式：2022-04-29T18:52:58.114304Z",
                        "type": "string"
                    },
                    "EndTime": {
                        "format": "date-time",
                        "description": "span结束时间，时间戳，接受格式：2022-04-29T18:52:58.114435Z",
                        "type": "string"
                    },
                    "Attributes": {
                        "nullable": true,
                        "description": "包含该span的属性的一个数组",
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/Attributes"
                        }
                    },
                    "Events": {
                        "nullable": true,
                        "description": "记录该span发生的一些事件信息",
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/Events"
                        }
                    },
                    "Links": {
                        "nullable": true,
                        "description": "相关联的其他的Span的信息",
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/Links"
                        }
                    },
                    "Status": {
                        "$ref": "#/components/schemas/Status",
                        "description": "设置的span的状态"
                    },
                    "DroppedAttributes": {
                        "description": "已减少的属性个数",
                        "type": "integer"
                    },
                    "DroppedEvents": {
                        "description": "已减少事件的个数",
                        "type": "integer"
                    },
                    "DroppedLinks": {
                        "description": "已减少关联span的个数",
                        "type": "integer"
                    },
                    "ChildSpanCount": {
                        "description": "具有子span的个数",
                        "type": "integer"
                    },
                    "Resource": {
                        "nullable": true,
                        "description": "一些资源字段信息",
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/Resource"
                        }
                    },
                    "InstrumentationLibrary": {
                        "$ref": "#/components/schemas/InstrumentationLibrary",
                        "description": "使用的工具库信息"
                    }
                },
                "example": {
                    "Name": "拉取服务",
                    "SpanContext": {
                        "TraceID": "ab4fe1de2d9c951411bbdbc3533d747f",
                        "SpanID": "44c39ef193f3e08a",
                        "TraceFlags": "01",
                        "TraceState": "rojo=00f067aa0ba902b7,congo=t61rcWkgMzE",
                        "Remote": false
                    },
                    "Parent": {
                        "TraceID": "ab4fe1de2d9c951411bbdbc3533d747f",
                        "SpanID": "dbff9e1d80069b58",
                        "TraceFlags": "01",
                        "TraceState": "rojo=00f067aa0ba902b7,congo=t61rcWkgMzE",
                        "Remote": false
                    },
                    "SpanKind": 1,
                    "StartTime": "2022-04-29T18:52:58.114304Z",
                    "EndTime": "2022-04-29T18:52:58.114435Z",
                    "Attributes": [
                        {
                            "Key": "输入的数字：",
                            "Value": {
                                "Type": "STRING",
                                "Value": "45"
                            }
                        }
                    ],
                    "Events": [
                        {
                            "Name": "Nice operation!",
                            "Attributes": [
                                {
                                    "Key": "bogons",
                                    "Value": {
                                        "Type": "INT",
                                        "Value": 100
                                    }
                                }
                            ],
                            "DroppedAttributeCount": 0,
                            "Time": "2022-04-29T18:52:58.114435Z"
                        }
                    ],
                    "Links": [
                        {
                            "TraceID": "ab4fe1de2d9c951411bbdbc3533d747k",
                            "SpanID": "dbff9e1d80069b58",
                            "TraceState": "rojo=00f067aa0ba902b7,congo=t61rcWkgMzE",
                            "Attributes": [
                                {
                                    "Key": "num1",
                                    "Value": {
                                        "Type": "INT",
                                        "Value": 100
                                    }
                                }
                            ]
                        }
                    ],
                    "Status": {
                        "Code": "Unset",
                        "Description": ""
                    },
                    "DroppedAttributes": 0,
                    "DroppedEvents": 0,
                    "DroppedLinks": 0,
                    "ChildSpanCount": 0,
                    "Resource": [
                        {
                            "Key": "service.name",
                            "Value": {
                                "Type": "STRING",
                                "Value": "斐波那契数列"
                            }
                        },
                        {
                            "Key": "service.version",
                            "Value": {
                                "Type": "STRING",
                                "Value": "版本1.0.1"
                            }
                        },
                        {
                            "Key": "telemetry.sdk.language",
                            "Value": {
                                "Type": "STRING",
                                "Value": "go"
                            }
                        },
                        {
                            "Key": "telemetry.sdk.name",
                            "Value": {
                                "Type": "STRING",
                                "Value": "opentelemetry"
                            }
                        },
                        {
                            "Key": "telemetry.sdk.version",
                            "Value": {
                                "Type": "STRING",
                                "Value": "1.9.0"
                            }
                        },
                        {
                            "Key": "环境",
                            "Value": {
                                "Type": "STRING",
                                "Value": "样例"
                            }
                        }
                    ],
                    "InstrumentationLibrary": {
                        "Name": "斐波",
                        "Version": "",
                        "SchemaURL": ""
                    }
                }
            },
            "Status": {
                "title": "Root Type for Status",
                "description": "设置的span的状态",
                "required": [
                    "Code",
                    "Description"
                ],
                "type": "object",
                "properties": {
                    "Code": {
                        "description": "状态码，处理异常时，可以将 Span 状态设置为Error，否则，Span状态将处于Unset（未设置）状态，Ok则表示该操作依据被软件开发者或操作者验证为成功完成",
                        "enum": [
                            "Unset",
                            "Ok",
                            "Error"
                        ],
                        "type": "string"
                    },
                    "Description": {
                        "description": "提供状态的描述性信息",
                        "type": "string"
                    }
                },
                "example": {
                    "Code": "Unset",
                    "Description": ""
                }
            },
            "Value": {
                "title": "Root Type for Value",
                "description": "对应某key值的类型、值",
                "required": [
                    "Type",
                    "Value"
                ],
                "type": "object",
                "properties": {
                    "Type": {
                        "description": "代表该属性的类型",
                        "enum": [
                            "BOOL",
                            "INT",
                            "FLOAT",
                            "STRING",
                            "BOOLARRAY",
                            "INTARRAY",
                            "FLOATARRAY",
                            "STRINGARRAY"
                        ],
                        "type": "string"
                    },
                    "Value": {
                        "description": "该属性的值，可以有多种类型"
                    }
                }
            },
            "Error": {
                "title": "Root Type for err_res",
                "description": "",
                "required": [
                    "code",
                    "description"
                ],
                "type": "object",
                "properties": {
                    "description": {
                        "description": "错误描述",
                        "type": "string"
                    },
                    "code": {
                        "description": "错误码",
                        "type": "string"
                    },
                    "details": {
                        "description": "错误详细信息",
                        "type": "object"
                    },
                    "link": {
                        "description": "错误信息地址",
                        "type": "string"
                    },
                    "solution": {
                        "description": "错误解决方法",
                        "type": "string"
                    }
                },
                "example": {
                    "description": "内部错误",
                    "code": "FeedIngester.InternalError.InternalError",
                    "details": {

                    },
                    "link": "some text",
                    "solution": "some text"
                }
            }
        }
    }
}